apiVersion: v1
kind: Service
metadata:
  name: llm-server
  labels:
    {{- include "machina.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.components.llmserver.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "machina.llmserver.selectorLabels" . | nindent 4 }}

