apiVersion: v1
kind: PersistentVolume
metadata:
  name: llm-server-pv
spec:
  capacity:
    storage: 64Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: "llm-hostpath"
  hostPath:
    path: /mnt/data/llm-server