apiVersion: v1
kind: PersistentVolume
metadata:
  name: llm-server-pv
spec:
  capacity:
    storage: 64Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: "llm-hostpath"
  hostPath:
    # path: /mnt/data/llm-server
    # path: /mnt/data/llm-server/.cache/huggingface
    # path: /home/edealba/.cache/huggingface/hub/models--TheBloke--OpenHermes-2.5-Mistral-7B-GPTQ
    path: /home/edealba/.cache/huggingface/hub/models--TheBloke--OpenHermes-2.5-Mistral-7B-GPTQ/blobs