apiVersion: v1
kind: PersistentVolume
metadata:
  name: llm-server-pv
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: "llm-hostpath"
  hostPath:
    path: /tmp/llm-server
